# Generated by Django 2.2.5 on 2019-09-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190919_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transac_header_date', models.DateField()),
                ('transac_header_name', models.CharField(max_length=50)),
                ('transac_header_total_amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('transac_detail_price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('transac_quantity', models.IntegerField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TransactionHeader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
