# Generated by Django 2.2.5 on 2019-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_transactiondetail_transactionheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionheader',
            name='transac_header_total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
