# Generated by Django 2.2.5 on 2019-09-27 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_transactionheader_transac_header_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionheader',
            name='transac_header_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 27, 16, 42, 55, 398695)),
        ),
    ]
